name: Generate docs and deploy GitHub Pages action

on:
  push:
    branches:
    - develop

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        path: aist_robotiq

    - name: Setup ROS
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: jazzy

    - name: apt update and upgrade
      run: |
        sudo apt update
        sudo apt upgrade -y

    - name: Install dependencies
      run: |
        sudo apt install python3-rosdoc2

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: aist_robotiq

    - name: Build HTML
      run: |
        mkdir docs
        cd docs
        rosdoc2 build --package-path ../aist_robotiq/aist_robotiq
        rosdoc2 build --package-path ../aist_robotiq/aist_robotiq_msgs
        cd ..

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./docs/aist_robotiq/docs_output

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

permissions:
  contents: write
  pages: write
  id-token: write
